export const theaterType = {
    GET_THEATER_LIST: "GET_THEATER_LIST",
    SET_DETAIL_MOVIE: "SET_DETAIL_MOVIE",
    FETCH_MOVIE_SCHEDULE: "FETCH_MOVIE_SCHEDULE",
    GET_LOADING_DETAIL: "GET_LOADING_DETAIL"
}