export const LazyType = {
    LOADING_LAZY_MOUNT: "LOADING_LAZY_MOUNT",
    LOADING_LAZY_UNMOUNT: "LOADING_LAZY_UNMOUNT",
    LOADING_BACKTO_HOME: "LOADING_BACKTO_HOME",
    LOADING_BACKTO_HOME_COMPLETED: "LOADING_BACKTO_HOME_COMPLETED"
}