export const DatVeType = {
    GET_DATVE: "GET_DATVE",
    EDIT_LIST_SEAT: "EDIT_LIST_SEAT",
    CHANGE_SELECTED_SEAT: "CHANGE_SELECTED_SEAT",
    BOOK_TICKET_SUCCESS: "BOOK_TICKET_SUCCESS",
    SET_DATA_TICKET_PAYMENT: "SET_DATA_TICKET_PAYMENT",
    SET_READY_TO_PAYMENT: "SET_READY_TO_PAYMENT",
    RESET_DATA_BOOKTICKET: "RESET_DATA_BOOKTICKET",
    TIMEOUT: "TIMEOUT",
    SET_ALERT_OVER: "SET_ALERT_OVER",
    RESET_ALERT_OVER: "RESET_ALERT_OVER",
    DAT_GHE: "DAT_GHE",
    LOADING_DATVE: "LOADING_DATVE"
}